export default {
  // auth
  CHECK_USER: 'CHECK_USER',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',

  // notes
  INSERT_NOTE: 'INSERT_NOTE',
  EDIT_NOTE: 'EDIT_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',

  // notes & public
  FETCH_NOTES: 'FETCH_NOTES',

  // admin
  FETCH_ALL_USERS: 'FETCH_ALL_USERS',
  UPDATE_USER: 'UPDATE_USER',

  // statistics
  FETCH_NUM_OF_NOTES: 'FETCH_NUM_OF_NOTES',
  FETCH_EDITED_NOTES: 'FETCH_EDITED_NOTES',
  FETCH_PUBLIC_NOTES: 'FETCH_PUBLIC_NOTES',
};
