export default {
  // all
  GET_ERROR_MESSAGE: 'ERROR_MESSAGE',

  // auth
  GET_AUTHTOKEN: 'GET_AUTHTOKEN',
  GET_USER: 'GET_USER',
  GET_USER_ID: 'GET_USER_ID',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  IS_ADMIN: 'IS_ADMIN',

  // notes & public
  GET_NOTES: 'GET_NOTES',

  // admin
  GET_USERS: 'GET_USERS',
  GET_USER_BY_NAME: 'GET_USER_BY_NAME',
  GET_NUM_OF_USERS: 'GET_NUM_OF_USERS',

  // statistics
  GET_NUM_OF_NOTES: 'GET_NUM_OF_NOTES',
  GET_NUM_OF_EDITED_NOTES: 'GET_NUM_OF_EDITED_NOTES',
  GET_NUM_OF_PUBLIC_NOTES: 'GET_NUM_OF_PUBLIC_NOTES',
};
