export default {
  // all
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',

  // auth
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_USER: 'SET_USER',

  // notes
  ADD_NOTE: 'ADD_NOTE',
  EDIT_NOTE: 'EDIT_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',

  // notes & public
  SET_NOTES: 'SET_NOTES',

  // admin
  SET_USERS: 'SET_USERS',
  UPDATE_USER: 'UPDATE_USER',

  // statistics
  SET_NUM_OF_NOTES: 'SET_NUM_OF_NOTES',
  SET_NUM_OF_EDITED_NOTES: 'SET_NUM_OF_EDITED_NOTES',
  SET_NUM_OF_MARKED_DONE_NOTES: 'SET_NUM_OF_MARKED_DONE_NOTES',
};
